export const menuData = [
  {
    category: "Starters",
    items: [
      { name: "Hara Bhara Kabab (8 pcs)", price: 110 },
      { name: "Paneer Tikka (8 pcs)", price: 150 },
      { name: "Corn Tikki (8 pcs)", price: 130 },
      { name: "Spring Roll (8 pcs)", price: 120 },
      { name: "Veg Cutlet", price: 90 },
      { name: "Chilli Paneer", price: 130 },
      { name: "Crispy Corn", price: 110 },
      { name: "French Fries", price: 80 },
      { name: "Veg Noodles", price: 60 },
      { name: "Veg Fried Rice", price: 70 },
      { name: "Veg Manchurian", price: 90 },
      { name: "Veg Manchurian Dry", price: 100 },
      { name: "Cheese Balls", price: 150 },
      { name: "French Roll", price: 110 },
      { name: "Chilli Roll", price: 120 },
      { name: "Paneer Roll", price: 140 },
      { name: "Veg Sandwich", price: 60 },
      { name: "Masala Sandwich", price: 70 },
      { name: "Cheese Sandwich", price: 90 },
      { name: "Club Sandwich", price: 100 },
      { name: "Veg Cheese Sandwich", price: 100 },
      { name: "Veg Cutlet Sandwich", price: 120 },
    ],
  },
  {
    category: "Paneer Main Course",
    items: [
      { name: "Matar Paneer", price: 130 },
      { name: "Palak Paneer", price: 130 },
      { name: "Paneer Chatpata", price: 150 },
      { name: "Paneer Bhurji [Gravy]", price: 150 },
      { name: "Paneer Bhurji [Dry]", price: 180 },
      { name: "Paneer Tikka Masala", price: 170 },
      { name: "Paneer kolhapuri", price: 170 },
      { name: "Paneer Angara", price: 170 },
      { name: "Paneer Pasanda", price: 190 },
      { name: "Paneer Hyderabadi", price: 170 },
      { name: "Paneer Punjabi", price: 170 },
      { name: "Kadhai Paneer", price: 150 },
      { name: "Handi Paneer", price: 160 },
      { name: "Kaju Curry [Sweet]", price: 170 },
      { name: "Shahi Paneer[Sweet]", price: 140 },
      { name: "Kaju Masala", price: 170 },
      { name: "Methi Matar Malai", price: 160 },
      { name: "Shahi Methi", price: 190 },
      { name: "Paneer Masala", price: 150 },
      { name: "Paneer Khada Masala", price: 160 },
      { name: "Shahi Do Pyaza", price: 150 },
      { name: "kaju Paneer", price: 160 },
      { name: "Butter Paneer Masala", price: 140 },
      { name: "Malai Kofta", price: 150 },
      { name: "Kaka Special", price: 200 },
    ],
  },
  {
    category: "Vegetable Main Course",
    items: [
      { name: "Sev Tamatar", price: 100 },
      { name: "Aloo Matar", price: 110 },
      { name: "Aloo Jeera", price: 110 },
      { name: "Dum Aloo", price: 120 },
      { name: "Bhindi Masala", price: 120 },
      { name: "Bhindi Fry", price: 120 },
      { name: "Bhindi Kurkuri", price: 120 },
      { name: "Aloo Matar Tamatar", price: 110 },
      { name: "Sev Bhaji [Veg]", price: 110 },
      { name: "Sev Bhaji [Doodh]", price: 110 },
      { name: "Bengan Masala", price: 110 },
      { name: "Bengan Bharta", price: 120 },
      { name: "Mix Veg", price: 140 },
      { name: "Veg Kolhapuri", price: 140 },
      { name: "Veg Kofta", price: 140 },
      { name: "Matar Masala", price: 130 },
      { name: "Chana Masala", price: 120 },
      { name: "Corn Palak", price: 120 },
      { name: "Aloo Palak", price: 110 },
      { name: "Aloo Do Pyaza", price: 110 },
      { name: "Aloo Punjabi", price: 130 },
      { name: "Capsicum Stuff", price: 130 },
      { name: "Mushroom Masala", price: 150 },
    ],
  },
    {
    category: "Indian Breads",
    items: [
      { name: "Tawa Plain Roti", price: 10 },
      { name: "Tawa Butter Roti", price: 12 },
      { name: "Tawa Paratha", price: 20 },
      { name: "Tandoori Roti Plain", price: 12 },
      { name: "Tandoori Roti Butter", price: 15 },
      { name: "Tandoori Lachha Paratha", price: 30 },
      { name: "Missi Roti", price: 30 },
      { name: "Tandoori Butter Naan", price: 40 },
      { name: "Garlic Naan", price: 50 },
      { name: "Cheese Garlic Naan", price: 70 },
      { name: "Paneer Paratha", price: 50 },
      { name: "Aloo Paratha", price: 40 },
      { name: "Butter Kulcha", price: 30 },
    ],
  },
  {
    category: "Rice",
    items: [
      { name: "Plain Rice", price: 90 },
      { name: "Jeera Rice", price: 100 },
      { name: "Masala Rice", price: 120 },
      { name: "Veg Pulao", price: 130 },
      { name: "Matar Pulao", price: 130 },
      { name: "Kashmir Pulao", price: 160 },
      { name: "Veg Biryani", price: 130 },
      { name: "Curd Rice", price: 130 },
      { name: "Butter Khichdi", price: 110 },
      { name: "Vegetable Khichdi", price: 120 },
      { name: "Punjabi Khichdi", price: 150 },
    ],
  },
   {
    category: "Dal",
    items: [
      { name: "Dal Fry", price: 100 },
      { name: "Jeera Dal", price: 100 },
      { name: "Hari Mirch Dal", price: 110 },
      { name: "Dal Tadka", price: 120 },
      { name: "Jain Dal", price: 100 },
      { name: "Dal Punjabi", price: 120 },
      { name: "Dal Makhni", price: 150 },
      { name: "Dal Pachrangi", price: 150 },
    ],
  },
  {
    category: "Soup",
    items: [
      { name: "Tomato Soup", price: 40 },
      { name: "Sweet Corn Soup", price: 50 },
      { name: "Hot and Sour Soup", price: 50 },
      { name: "Manchow Soup", price: 50 },
    ],
  },
  {
    category: "Salad",
    items: [
      { name: "Green Salad", price: 40 },
      { name: "Onion Salad", price: 20 },
      { name: "Peanut Salad", price: 20 },
      { name: "Punjabi Salad", price: 50 },
      { name: "Lemon Salad", price: 40 },
    ],
  },
  {
    category: "Combos / Thali",
    items: [
      { name: "Chole Bhature Combo", price: 99 },
      { name: "Chole Kulche Combo", price: 99 },
      { name: "Dal Chawal", price: 80 },
      { name: "Dal Bafla Combo", price: 99 },
      { name: "Makki Roti Sarson Saag Combo", price: 99 },
      { name: "Regular Thali", price: 80 },
      { name: "Shahi Thali", price: 120 },
    ],
  },
  {
    category: "Beverages",
    items: [
      { name: "Tea", price: 25 },
      { name: "Hot Coffee", price: 55 },
      { name: "Cold Coffee", price: 60 },
      { name: "Lassi", price: 40 },
      { name: "Butter Milk", price: 30 },
      { name: "Fresh Lime Water", price: 30 },
    ],
  },
  {
    category: "Desserts",
    items: [
      { name: "Gulab Jamun (2 pcs)", price: 40 },
      { name: "Ice Cream", price: 50 },
    ],
  },
];
